### ISSUE TITLE
Implement network policies for warden components

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/warden#416]
**Description**

The necessary network policies have to be created to allow the warden admission and warden operator Pods to perform (only) the communictions needed.

Acceptance criteria:
- Warden can perform the network connections as required
- Warden still work even a deny-all policy is in place

**Reasons**

Improve cluster security and allow customer to establish a deny-all policy

**Attachments**

**Comment by TorstenD-SAP** [comment]
According to the network traces I created the following policies are needed:

Warden to DNS:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyma-project.io--warden-to-dns
  namespace: default
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: node-local-dns
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - ports:
        - port: 8053
          protocol: UDP
        - port: 8053
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  podSelector:
    matchLabels:
      kyma-project.io/module: warden
  policyTypes:
    - Egress
```
  
Shoot VPN to Warden:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyma-project.io--seed-to-warden
  namespace: default
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              gardener.cloud/purpose: kube-system
          podSelector:
            matchLabels:
              app: vpn-shoot
  podSelector:
    matchLabels:
      kyma-project.io/module: warden
  policyTypes:
    - Ingress

```
Warden to the API Server:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyma-project.io--warden-to-apiserver
  namespace: default
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
  podSelector:
    matchLabels:
      kyma-project.io/module: warden
  policyTypes:
    - Egress
```
